# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  devhabitapi:
    image: devhabitapi
    container_name: devhabit.api
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:5000
      - 8081:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
