# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  devhabitapi:
    image: devhabitapi
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
    ports:
      - "8080:5000"
      - "8081:5001"
