Put http://localhost:5000/github/personal-access-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbWJlciIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NzE1Njk3LCJpYXQiOjE3NDg3MTIwOTcsIm5iZiI6MTc0ODcxMjA5N30.BwLT3PhfHemTjyRS_Mbjtc8ZjX0fsMe5AuaITjxp1ro

{
    "Token": "redacted"
}

###
Get http://localhost:5000/github/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbWJlciIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NzIzMTY3LCJpYXQiOjE3NDg3MTk1NjcsIm5iZiI6MTc0ODcxOTU2N30.x4Z_qsXYUEIB_kFRaN5GlghIOlj9zQjfDmzSMFsnlWA

###
Get http://localhost:5000/github/events?username=omlnaut
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbWJlciIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NzIzMTY3LCJpYXQiOjE3NDg3MTk1NjcsIm5iZiI6MTc0ODcxOTU2N30.x4Z_qsXYUEIB_kFRaN5GlghIOlj9zQjfDmzSMFsnlWA