Get http://localhost:5000/github?accessToken=redacted
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbWJlciIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NjQyNDg5LCJpYXQiOjE3NDg2Mzg4ODksIm5iZiI6MTc0ODYzODg4OX0.8gi726y8y_UkCQnP-_lvcyzWeJK6yZmgkR6sH7M_6Eo