POST http://localhost:5000/tags
Content-Type: application/json

{
    "name": "NewTagi",
    "description": "This is an example tag description"
}

###

GET http://localhost:5000/habits?sort=description asc&pageSize=3&fields=Name, DescRiptIon
Content-Type: application/json

###
GET http://localhost:5000/habits/h_c6b69c6e-9729-4b3c-8d4b-084ce4576a0c?fields=Id,Name, DescRiptIon
Content-Type: application/json

###