POST http://localhost:5000/tags
Content-Type: application/json

{
    "name": "NewTagi",
    "description": "This is an example tag description"
}

###

GET http://localhost:5000/habits?sort=description asc&pageSize=2&page=5
Content-Type: application/json

###