POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "Email": "asdf@dev.com",
    "Name": "testi",
    "Password": "123aA!",
    "ConfirmPassword": "123aA!"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "Email": "asdf@dev.com",
    "Password": "123aA!",
}

###
POST http://localhost:5000/seed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NTUwMzQ5LCJpYXQiOjE3NDg1NDY3NDksIm5iZiI6MTc0ODU0Njc0OX0.HkunCEZF0Ht9tSPyBOrrxCYqGv078QrhosNB2a1hr5s

###
Get http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGEyZWY5Ni0yOGJhLTQwNzUtOTdlMC0xNjg0MzBiYTdkMjQiLCJlbWFpbCI6ImFzZGZAZGV2LmNvbSIsImF1ZCI6ImRldi1oYWJpdC5hcHAiLCJpc3MiOiJkZXYtaGFiaXQuYXBpIiwiZXhwIjoxNzQ4NDY1ODYzLCJpYXQiOjE3NDg0NjIyNjMsIm5iZiI6MTc0ODQ2MjI2M30.6duMcWOZNiUfKZKy8fYEBTNhwcposOtf5qEu29BBCrs

###
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "Token": "Lxdc1elOpgMkAgvJgVo2vA+5X+7XaLtGNKg48OFTsJg=",
}
###
GET http://localhost:5000/users/u_f3a81c44-7920-4cb2-acc3-023588f9c80f
Accept: application/json;v=1